# Generated by Django 5.0.7 on 2024-07-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',), 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='shoe',
            options={'verbose_name': 'Shoe', 'verbose_name_plural': 'Shoes'},
        ),
        migrations.AlterModelOptions(
            name='shoesize',
            options={'verbose_name': 'Shoe Size', 'verbose_name_plural': 'Shoes Sizes'},
        ),
    ]
