# Generated by Django 5.0.7 on 2024-07-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
