# Generated by Django 5.0.7 on 2024-07-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
