# Generated by Django 5.0.7 on 2024-07-27 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_remove_order_total_price'),
        ('shoe_app', '0002_shoe_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='order_app.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='shoe_app.shoe', verbose_name='Shoe'),
        ),
    ]
